@echo off
REM This file was generated by auto-py-to-exe.
pyinstaller --noconfirm --onefile --windowed --icon "C:\Users\tom20\Desktop\1\Vacuum Music Player\vacuum_music_player.ico" --add-data "C:\Users\tom20\Desktop\1\Vacuum Music Player\vacuum_music_player.ico;." --add-data "C:\Users\tom20\Desktop\1\Vacuum Music Player\AcrylicEffect;AcrylicEffect/"  "C:\Users\tom20\Desktop\1\Vacuum Music Player\music_player.py"
pause
